Updated build

diff --git a/.github/workflows/ci_build.yml b/.github/workflows/ci_build.yml
--- a/.github/workflows/ci_build.yml
+++ b/.github/workflows/ci_build.yml
@@ -19,7 +19,11 @@ jobs:
       run: |
         xcodebuild -showsdks
     - name: Xcodebuild Action
-      uses: mxcl/xcodebuild@v1
+      run: |
+        xcodebuild -project ./Mlem.xcodeproj -scheme "Mlem" -sdk "iphonesimulator16.2" -quiet -resultBundlePath "build_results.xcresult"
+    - uses: kishikawakatsumi/xcresulttool@v1
       with:
-        workspace: "Mlem.xcodeproj/project.xcworkspace"
-        scheme: "Mlem"
+        path: build_results.xcresult
+      if: success() || failure()
+      # ^ This is important because the action will be run
+      # even if the test fails in the previous step.
